# Generated by Django 3.0.3 on 2020-12-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='connetWithMe',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.IntegerField(default=0),
        ),
    ]
