# Generated by Django 3.0.3 on 2020-12-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
    ]
